spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/servicelens

servicelens:
  prometheus:
    base-url: http://prometheus:9090

management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
